// Generated by gencpp from file waypoint_navigator/ExecutePathFromFileResponse.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILERESPONSE_H
#define WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_navigator
{
template <class ContainerAllocator>
struct ExecutePathFromFileResponse_
{
  typedef ExecutePathFromFileResponse_<ContainerAllocator> Type;

  ExecutePathFromFileResponse_()
    {
    }
  ExecutePathFromFileResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecutePathFromFileResponse_

typedef ::waypoint_navigator::ExecutePathFromFileResponse_<std::allocator<void> > ExecutePathFromFileResponse;

typedef boost::shared_ptr< ::waypoint_navigator::ExecutePathFromFileResponse > ExecutePathFromFileResponsePtr;
typedef boost::shared_ptr< ::waypoint_navigator::ExecutePathFromFileResponse const> ExecutePathFromFileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_navigator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mav_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mav_planning_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_planning_msgs/msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navigator/ExecutePathFromFileResponse";
  }

  static const char* value(const ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecutePathFromFileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::waypoint_navigator::ExecutePathFromFileResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILERESPONSE_H
