// Generated by gencpp from file waypoint_navigator/ExecutePathFromFile.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILE_H
#define WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILE_H

#include <ros/service_traits.h>


#include <waypoint_navigator/ExecutePathFromFileRequest.h>
#include <waypoint_navigator/ExecutePathFromFileResponse.h>


namespace waypoint_navigator
{

struct ExecutePathFromFile
{

typedef ExecutePathFromFileRequest Request;
typedef ExecutePathFromFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutePathFromFile
} // namespace waypoint_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_navigator::ExecutePathFromFile > {
  static const char* value()
  {
    return "716e25f9d9dc76ceba197f93cbf05dc7";
  }

  static const char* value(const ::waypoint_navigator::ExecutePathFromFile&) { return value(); }
};

template<>
struct DataType< ::waypoint_navigator::ExecutePathFromFile > {
  static const char* value()
  {
    return "waypoint_navigator/ExecutePathFromFile";
  }

  static const char* value(const ::waypoint_navigator::ExecutePathFromFile&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_navigator::ExecutePathFromFileRequest> should match 
// service_traits::MD5Sum< ::waypoint_navigator::ExecutePathFromFile > 
template<>
struct MD5Sum< ::waypoint_navigator::ExecutePathFromFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::ExecutePathFromFile >::value();
  }
  static const char* value(const ::waypoint_navigator::ExecutePathFromFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::ExecutePathFromFileRequest> should match 
// service_traits::DataType< ::waypoint_navigator::ExecutePathFromFile > 
template<>
struct DataType< ::waypoint_navigator::ExecutePathFromFileRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::ExecutePathFromFile >::value();
  }
  static const char* value(const ::waypoint_navigator::ExecutePathFromFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_navigator::ExecutePathFromFileResponse> should match 
// service_traits::MD5Sum< ::waypoint_navigator::ExecutePathFromFile > 
template<>
struct MD5Sum< ::waypoint_navigator::ExecutePathFromFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::ExecutePathFromFile >::value();
  }
  static const char* value(const ::waypoint_navigator::ExecutePathFromFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::ExecutePathFromFileResponse> should match 
// service_traits::DataType< ::waypoint_navigator::ExecutePathFromFile > 
template<>
struct DataType< ::waypoint_navigator::ExecutePathFromFileResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::ExecutePathFromFile >::value();
  }
  static const char* value(const ::waypoint_navigator::ExecutePathFromFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_EXECUTEPATHFROMFILE_H
