// Generated by gencpp from file waypoint_navigator/GoToWaypoint.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_GOTOWAYPOINT_H
#define WAYPOINT_NAVIGATOR_MESSAGE_GOTOWAYPOINT_H

#include <ros/service_traits.h>


#include <waypoint_navigator/GoToWaypointRequest.h>
#include <waypoint_navigator/GoToWaypointResponse.h>


namespace waypoint_navigator
{

struct GoToWaypoint
{

typedef GoToWaypointRequest Request;
typedef GoToWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToWaypoint
} // namespace waypoint_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_navigator::GoToWaypoint > {
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::waypoint_navigator::GoToWaypoint&) { return value(); }
};

template<>
struct DataType< ::waypoint_navigator::GoToWaypoint > {
  static const char* value()
  {
    return "waypoint_navigator/GoToWaypoint";
  }

  static const char* value(const ::waypoint_navigator::GoToWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_navigator::GoToWaypointRequest> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToWaypoint > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToWaypoint >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToWaypointRequest> should match 
// service_traits::DataType< ::waypoint_navigator::GoToWaypoint > 
template<>
struct DataType< ::waypoint_navigator::GoToWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToWaypoint >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_navigator::GoToWaypointResponse> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToWaypoint > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToWaypoint >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToWaypointResponse> should match 
// service_traits::DataType< ::waypoint_navigator::GoToWaypoint > 
template<>
struct DataType< ::waypoint_navigator::GoToWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToWaypoint >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_GOTOWAYPOINT_H
