// Generated by gencpp from file waypoint_navigator/GoToHeight.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHT_H
#define WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHT_H

#include <ros/service_traits.h>


#include <waypoint_navigator/GoToHeightRequest.h>
#include <waypoint_navigator/GoToHeightResponse.h>


namespace waypoint_navigator
{

struct GoToHeight
{

typedef GoToHeightRequest Request;
typedef GoToHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToHeight
} // namespace waypoint_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_navigator::GoToHeight > {
  static const char* value()
  {
    return "1408bf479b7f0dca197fee4d8d8ed1d0";
  }

  static const char* value(const ::waypoint_navigator::GoToHeight&) { return value(); }
};

template<>
struct DataType< ::waypoint_navigator::GoToHeight > {
  static const char* value()
  {
    return "waypoint_navigator/GoToHeight";
  }

  static const char* value(const ::waypoint_navigator::GoToHeight&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_navigator::GoToHeightRequest> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToHeight > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToHeight >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToHeightRequest> should match 
// service_traits::DataType< ::waypoint_navigator::GoToHeight > 
template<>
struct DataType< ::waypoint_navigator::GoToHeightRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToHeight >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_navigator::GoToHeightResponse> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToHeight > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToHeight >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToHeightResponse> should match 
// service_traits::DataType< ::waypoint_navigator::GoToHeight > 
template<>
struct DataType< ::waypoint_navigator::GoToHeightResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToHeight >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHT_H
