// Generated by gencpp from file waypoint_navigator/GoToPoseWaypointsRequest.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTSREQUEST_H
#define WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <std_msgs/String.h>

namespace waypoint_navigator
{
template <class ContainerAllocator>
struct GoToPoseWaypointsRequest_
{
  typedef GoToPoseWaypointsRequest_<ContainerAllocator> Type;

  GoToPoseWaypointsRequest_()
    : waypoints()
    , mission_id()  {
    }
  GoToPoseWaypointsRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , mission_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;

   typedef  ::std_msgs::String_<ContainerAllocator>  _mission_id_type;
  _mission_id_type mission_id;





  typedef boost::shared_ptr< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPoseWaypointsRequest_

typedef ::waypoint_navigator::GoToPoseWaypointsRequest_<std::allocator<void> > GoToPoseWaypointsRequest;

typedef boost::shared_ptr< ::waypoint_navigator::GoToPoseWaypointsRequest > GoToPoseWaypointsRequestPtr;
typedef boost::shared_ptr< ::waypoint_navigator::GoToPoseWaypointsRequest const> GoToPoseWaypointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_navigator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mav_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mav_planning_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_planning_msgs/msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b363140d3a9fe53d1402ab7ca233130";
  }

  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b363140d3a9fe53ULL;
  static const uint64_t static_value2 = 0xd1402ab7ca233130ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navigator/GoToPoseWaypointsRequest";
  }

  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Pose[] waypoints\n\
std_msgs/String mission_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.mission_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPoseWaypointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_navigator::GoToPoseWaypointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "mission_id: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.mission_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTSREQUEST_H
