// Generated by gencpp from file waypoint_navigator/GoToHeightRequest.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHTREQUEST_H
#define WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64.h>

namespace waypoint_navigator
{
template <class ContainerAllocator>
struct GoToHeightRequest_
{
  typedef GoToHeightRequest_<ContainerAllocator> Type;

  GoToHeightRequest_()
    : height()  {
    }
  GoToHeightRequest_(const ContainerAllocator& _alloc)
    : height(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64_<ContainerAllocator>  _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToHeightRequest_

typedef ::waypoint_navigator::GoToHeightRequest_<std::allocator<void> > GoToHeightRequest;

typedef boost::shared_ptr< ::waypoint_navigator::GoToHeightRequest > GoToHeightRequestPtr;
typedef boost::shared_ptr< ::waypoint_navigator::GoToHeightRequest const> GoToHeightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace waypoint_navigator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mav_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mav_planning_msgs': ['/home/ardalan/catkin_ws/src/mav_comm/mav_planning_msgs/msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1408bf479b7f0dca197fee4d8d8ed1d0";
  }

  static const char* value(const ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1408bf479b7f0dcaULL;
  static const uint64_t static_value2 = 0x197fee4d8d8ed1d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navigator/GoToHeightRequest";
  }

  static const char* value(const ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/Float64 height\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToHeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_navigator::GoToHeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_GOTOHEIGHTREQUEST_H
