// Generated by gencpp from file waypoint_navigator/GoToPoseWaypoints.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTS_H
#define WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTS_H

#include <ros/service_traits.h>


#include <waypoint_navigator/GoToPoseWaypointsRequest.h>
#include <waypoint_navigator/GoToPoseWaypointsResponse.h>


namespace waypoint_navigator
{

struct GoToPoseWaypoints
{

typedef GoToPoseWaypointsRequest Request;
typedef GoToPoseWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPoseWaypoints
} // namespace waypoint_navigator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_navigator::GoToPoseWaypoints > {
  static const char* value()
  {
    return "0b363140d3a9fe53d1402ab7ca233130";
  }

  static const char* value(const ::waypoint_navigator::GoToPoseWaypoints&) { return value(); }
};

template<>
struct DataType< ::waypoint_navigator::GoToPoseWaypoints > {
  static const char* value()
  {
    return "waypoint_navigator/GoToPoseWaypoints";
  }

  static const char* value(const ::waypoint_navigator::GoToPoseWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_navigator::GoToPoseWaypointsRequest> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToPoseWaypoints > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToPoseWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToPoseWaypoints >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToPoseWaypointsRequest> should match 
// service_traits::DataType< ::waypoint_navigator::GoToPoseWaypoints > 
template<>
struct DataType< ::waypoint_navigator::GoToPoseWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToPoseWaypoints >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_navigator::GoToPoseWaypointsResponse> should match 
// service_traits::MD5Sum< ::waypoint_navigator::GoToPoseWaypoints > 
template<>
struct MD5Sum< ::waypoint_navigator::GoToPoseWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_navigator::GoToPoseWaypoints >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_navigator::GoToPoseWaypointsResponse> should match 
// service_traits::DataType< ::waypoint_navigator::GoToPoseWaypoints > 
template<>
struct DataType< ::waypoint_navigator::GoToPoseWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_navigator::GoToPoseWaypoints >::value();
  }
  static const char* value(const ::waypoint_navigator::GoToPoseWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_NAVIGATOR_MESSAGE_GOTOPOSEWAYPOINTS_H
